### ISSUE TITLE
Reporting is not triggered when Quarkus Master build fails

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus-ecosystem-ci#47]
After speaking with @geoand , it seems that when the Quarkus Master build fails, the reporting system is not triggered and then the status for the target repository is green. 

The fact of that Quarkus Master build is a bit odd and unexpected, but it has already happened:

https://github.com/quarkus-qe/beefy-scenarios/runs/2109815817?check_suite_focus=true

According to @geoand , this needs fixing:

- It's just a matter of capturing the exit code of https://github.com/quarkusio/quarkus-ecosystem-ci/blob/master/setup-and-test#L33
- And launching the report script if it fails: https://github.com/quarkusio/quarkus-ecosystem-ci/blob/master/setup-and-test#L86

**Comment by geoand** [comment]
Thanks for capturing this info
